storage: STORAGE
keystore: KEYSTORE
algorithm: ALGORITHM
secret:
  saltLength: SALT_LENGTH
  length: SECRET_LENGTH
  digest: SECRET_DIGEST
  iterations: HASH_ITERATIONS
  alphabet: SECRET_ALPHABET
  ignoreChars: IGNORE_CHARS
